---
pr_municipality:
  "PR.AJ": "Adjuntas"
  "PR.AD": "Aguada"
  "PR.AL": "Aguadilla"
  "PR.AB": "Aguas Buenas"
  "PR.AI": "Aibonito"
  "PR.AN": "Añasco"
  "PR.AC": "Arecibo"
  "PR.AR": "Arroyo"
  "PR.BC": "Barceloneta"
  "PR.BQ": "Barranquitas"
  "PR.BY": "Bayamón"
  "PR.CR": "Cabo Rojo"
  "PR.CG": "Caguas"
  "PR.CA": "Camuy"
  "PR.CV": "Canóvanas"
  "PR.CN": "Carolina"
  "PR.CT": "Cataño"
  "PR.CY": "Cayey"
  "PR.CB": "Ceiba"
  "PR.CL": "Ciales"
  "PR.CD": "Cidra"
  "PR.CO": "Coamo"
  "PR.CM": "Comerio"
  "PR.CZ": "Corozal"
  "PR.CU": "Culebra"
  "PR.DO": "Dorado"
  "PR.FJ": "Fajardo"
  "PR.FL": "Florida"
  "PR.GC": "Guánica"
  "PR.GM": "Guayama"
  "PR.GL": "Guayanilla"
  "PR.GB": "Guaynabo"
  "PR.GR": "Gurabo"
  "PR.HA": "Hatillo"
  "PR.HO": "Hormigueros"
  "PR.HU": "Humacao"
  "PR.IS": "Isabela"
  "PR.JY": "Jayuya"
  "PR.JD": "Juana Díaz"
  "PR.JC": "Juncos"
  "PR.LJ": "Lajas"
  "PR.LR": "Lares"
  "PR.LM": "Las Marías"
  "PR.LP": "Las Piedras"
  "PR.LZ": "Loíza"
  "PR.LQ": "Luquillo"
  "PR.MT": "Manatí"
  "PR.MR": "Maricao"
  "PR.MB": "Maunabo"
  "PR.MG": "Mayagüez"
  "PR.MC": "Moca"
  "PR.MV": "Morovis"
  "PR.NG": "Naguabo"
  "PR.NR": "Naranjito"
  "PR.OR": "Orocovis"
  "PR.PT": "Patillas"
  "PR.PN": "Peñuelas"
  "PR.PO": "Ponce"
  "PR.QB": "Quebradillas"
  "PR.RC": "Rincón"
  "PR.RG": "Río Grande"
  "PR.SB": "Sabana Grande"
  "PR.SA": "Salinas"
  "PR.SG": "San Germán"
  "PR.SJ": "San Juan"
  "PR.SL": "San Lorenzo"
  "PR.SS": "San Sebastián"
  "PR.SI": "Santa Isabel"
  "PR.TA": "Toa Alta"
  "PR.TB": "Toa Baja"
  "PR.TJ": "Trujillo Alto"
  "PR.UT": "Utuado"
  "PR.VA": "Vega Alta"
  "PR.VB": "Vega Baja"
  "PR.VQ": "Vieques"
  "PR.VL": "Villalba"
  "PR.YB": "Yabucoa"
  "PR.YU": "Yauco"
...
